-- USER SQL
CREATE USER "REST_DB_LINK_API" IDENTIFIED BY "REST_DB_LINK_API"  
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "REST_DB_LINK_API" QUOTA UNLIMITED ON "DATA";

-- ROLES

-- SYSTEM PRIVILEGES
GRANT CREATE VIEW TO "REST_DB_LINK_API" ;
GRANT CREATE SESSION TO "REST_DB_LINK_API" ;
GRANT CREATE TABLE TO "REST_DB_LINK_API" ;
GRANT CREATE TABLESPACE TO "REST_DB_LINK_API" ;
GRANT CREATE PROCEDURE TO "REST_DB_LINK_API" ;
GRANT EXECUTE ON UTL_HTTP TO "REST_DB_LINK_API" ;
