DECLARE
  lv_count number := 0;
BEGIN

  SELECT COUNT(*) 
  INTO lv_count
  FROM DBA_USERS
  WHERE USERNAME = 'REST_DB_LINK_API';

  IF lv_count > 0 THEN      
    EXECUTE IMMEDIATE 'DROP USER REST_DB_LINK_API CASCADE';
  END IF;

END;
/
-- USER SQL
CREATE USER "REST_DB_LINK_API" IDENTIFIED BY "REST_DB_LINK_API"  
TEMPORARY TABLESPACE "TEMP";

-- ROLES

-- SYSTEM PRIVILEGES
GRANT CREATE SESSION TO "REST_DB_LINK_API" ;
GRANT CREATE TABLE TO "REST_DB_LINK_API" ;
GRANT CREATE PROCEDURE TO "REST_DB_LINK_API" ;
GRANT EXECUTE ON UTL_HTTP TO "REST_DB_LINK_API" ;
